# Book settings
title                       : Little Notes  # The title of the book. Will be placed in the left navbar.
author                      : Le Nhut Nam  # The author of the book
copyright                   : "{% now 'local', '%Y' %}"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/namlnhut/little-notes
  path_to_book: little-notes
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

# Sphinx configuration
sphinx:
  config:
    html_theme_options:
      navigation_with_keys: true
